language: node_js

node_js:
  - "6.1"

sudo: required

branches:
  only:
    - master
    - /^greenkeeper/.*$/

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run lint

