language: node_js

node_js:
  - "6.1"

sudo: required

branches:
  only:
    - master

cache:
  directories:
    - "node_modules"

install:
  - npm install

script:
  - npm run lint

notifications:
  email:
    on_success: never
    on_failure: always
